### ISSUE TITLE
Should only checkout conformance tests from the `main` branch

### ISSUE THREAD

**Issue by mr-c** [tom-tan/cwl-run-conformance-tests#1]
which is not necessarily the default branch.

For example, the default branch of https://github.com/common-workflow-language/cwl-v1.2/ is `1.2.1_proposed` but that has not been ratified by the CWL Leadership Team; therefore the branch `main` should instead be checked out.

Could add an option to specify another branch instead..

**Comment by tom-tan** [comment]
Thank you for your comment!
I will update the code to checkout `main` branch instead of the default branch.

> Could add an option to specify another branch instead..

How about introducing `enable-dev` option to enable options such as `branch` field?
It makes clearer that the CI workflow tests for non-released version and makes easier to introduce other kinds of advanced options such as `cwlVersion: v1.3` (this example looses the version checking to enable testing for the next release).

For example:

```yaml
- name: Run conformance tests
  uses: tom-tan/cwl-run-conformance-tests@v1.0.0
  with:
    cwlVersion: v1.0
    runner: cwltool
    timeout: 30
    enable-dev: true # enable advanced options
    branch: 1.2.1_proposed # It is valid only when `enable-dev: true` and tests specified branch
```
or
```yaml
- name: Run conformance tests
  uses: tom-tan/cwl-run-conformance-tests@v1.0.0
  with:
    cwlVersion: v1.3 # tests for the next release of CWL
    runner: cwltool
    timeout: 30
    enable-dev: true # enable advanced options
```
